"""Encrypted session abstraction over the X25519+HKDF+AESGCM primitives.

A ``Session`` binds two peer public keys to a pair of symmetric send/recv
chains.  It is the unit a chat client, file-transfer worker, or any other
caller actually holds in memory: ``send(plaintext) -> ciphertext`` and
``recv(ciphertext) -> plaintext`` are the only methods needed.

The class deliberately contains no I/O, no framing, and no key-rotation
logic — those concerns belong in higher layers.  What it *does* guarantee
is that no nonce is ever reused within the lifetime of a session, by
delegating to :class:`e2e.nonce_manager.NonceManager`.

Wire format expected on ``recv`` (and produced by ``send``)::

    header  (8 bytes, big-endian)  : counter used for the outgoing nonce
    payload (variable)              : AES-GCM ciphertext including 16-byte tag

The header is unauthenticated; the AEAD tag on the payload authenticates
both the plaintext and the associated header bytes, so an attacker cannot
flip the counter without detection.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass
from typing import Optional

from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey, X25519PublicKey
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

from .nonce_manager import NonceManager, NonceExhausted


HEADER_FMT = ">Q"  # unsigned 64-bit big-endian counter
HEADER_LEN = struct.calcsize(HEADER_FMT)
INFO_SEND = b"technocore-e2e/v1/send"
INFO_RECV = b"technocore-e2e/v1/recv"


class SessionError(Exception):
    """Base error for session-level failures."""


class SessionClosed(SessionError):
    """Raised when send/recv is attempted after close()."""


class FrameError(SessionError):
    """Raised when an inbound frame is malformed or fails authentication."""


@dataclass
class PeerKeys:
    """Convenience container for a local keypair and a remote public key."""

    local_private: X25519PrivateKey
    remote_public: X25519PublicKey

    @classmethod
    def from_bytes(
        cls,
        local_private_bytes: bytes,
        remote_public_bytes: bytes,
    ) -> "PeerKeys":
        if len(local_private_bytes) != 32:
            raise ValueError("local private key must be 32 bytes")
        if len(remote_public_bytes) != 32:
            raise ValueError("remote public key must be 32 bytes")
        return cls(
            local_private=X25519PrivateKey.from_private_bytes(local_private_bytes),
            remote_public=X25519PublicKey.from_public_bytes(remote_public_bytes),
        )


class Session:
    """A bidirectional encrypted channel between two peers.

    Parameters
    ----------
    keys:
        Local private key plus the remote peer's public key.
    salt:
        Optional HKDF salt.  Should be unique per session; passing ``None``
        is safe but slightly weakens domain separation.
    """

    def __init__(self, keys: PeerKeys, salt: Optional[bytes] = None) -> None:
        self._keys = keys
        self._salt = salt or b""
        self._closed = False
        self._send_aead, self._recv_aead = self._derive_aeads()
        self._send_nonces = NonceManager()
        self._recv_nonces = NonceManager()

    # ------------------------------------------------------------------
    # Key derivation
    # ------------------------------------------------------------------
    def _derive_aeads(self) -> tuple[AESGCM, AESGCM]:
        shared = self._keys.local_private.exchange(self._keys.remote_public)
        # Derive 64 bytes: first 32 for send, next 32 for recv.
        okm = HKDF(
            algorithm=hashes.SHA256(),
            length=64,
            salt=self._salt or None,
            info=b"technocore-e2e/v1/keys",
        ).derive(shared)
        return AESGCM(okm[:32]), AESGCM(okm[32:])

    # ------------------------------------------------------------------
    # Wire I/O
    # ------------------------------------------------------------------
    def send(self, plaintext: bytes, aad: bytes = b"") -> bytes:
        """Encrypt ``plaintext`` and return a self-contained frame.

        The returned bytes are: ``counter(8) || nonce(12) || ciphertext+tag``.
        The nonce is generated by :class:`NonceManager` so it is never
        reused within this session.
        """
        if self._closed:
            raise SessionClosed("session is closed")
        try:
            counter, nonce = self._send_nonces.next()
        except NonceExhausted as exc:
            raise SessionClosed(str(exc)) from exc
        header = struct.pack(HEADER_FMT, counter)
        # The header is the AAD so tampering is detected by the AEAD tag.
        ct = self._send_aead.encrypt(nonce, plaintext, header + aad)
        return header + nonce + ct

    def recv(self, frame: bytes) -> bytes:
        """Decrypt a frame previously produced by :meth:`send`."""
        if self._closed:
            raise SessionClosed("session is closed")
        if len(frame) < HEADER_LEN + 12 + 16:
            raise FrameError("frame too short")
        header = frame[:HEADER_LEN]
        nonce = frame[HEADER_LEN : HEADER_LEN + 12]
        ct = frame[HEADER_LEN + 12 :]
        counter = struct.unpack(HEADER_FMT, header)[0]
        try:
            self._recv_nonces.check_inbound(counter)
        except NonceExhausted as exc:
            raise FrameError(str(exc)) from exc
        try:
            plaintext = self._recv_aead.decrypt(nonce, ct, header)
        except Exception as exc:  # InvalidTag etc.
            raise FrameError(f"decryption failed: {exc}") from exc
        return plaintext

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------
    def close(self) -> None:
        """Mark the session as closed.  Idempotent."""
        self._closed = True

    @property
    def is_closed(self) -> bool:
        return self._closed

    @property
    def send_counter(self) -> int:
        """Number of frames already sent (useful for diagnostics/tests)."""
        return self._send_nonces.count

    @property
    def recv_counter(self) -> int:
        return self._recv_nonces.count

    # ------------------------------------------------------------------
    # Dunder helpers
    # ------------------------------------------------------------------
    def __enter__(self) -> "Session":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()

<!-- Authored by Technocore agent DID did:key:z6MkwUFX8bCp4RZUyG3fod2wEVvRci7AY2h19fJWELAsomiC -->
